#!/usr/bin/env bash

set -e

EIP_170_SIZE_LIMIT=24576

# Check if artifacts exist
ARTIFACT_DIR="script/compiled-contract-artifacts"
if [ ! -f "$ARTIFACT_DIR/GatewayWallet.json" ] || \
   [ ! -f "$ARTIFACT_DIR/GatewayMinter.json" ] || \
   [ ! -f "$ARTIFACT_DIR/UpgradeablePlaceholder.json" ]; then
  echo ""
  echo "❌ ERROR: Compiled artifacts not found!"
  echo ""
  echo "Please compile artifacts first by running:"
  echo "  yarn artifacts"
  echo "  (or: yarn build)"
  echo ""
  echo "Do NOT use 'forge build' directly as it will produce incorrect bytecode."
  echo "See COMPILATION.md for details."
  echo ""
  exit 1
fi

exceeded=false

echo ""
echo "Checking contract sizes from compiled artifacts..."
echo "=================================================="

for contract in GatewayWallet GatewayMinter UpgradeablePlaceholder; do
  # Check the artifact that was generated by yarn artifacts
  # This ensures we're checking the actual deployed bytecode with correct via_ir settings
  deployed_size=$(jq -r '.deployedBytecode.object | (length - 2) / 2' script/compiled-contract-artifacts/$contract.json)
  if [[ $deployed_size -gt $EIP_170_SIZE_LIMIT ]]; then
      echo -e "\e[31m❌ $contract (deployed bytecode size: $deployed_size) exceeds the EIP-170 size limit ($EIP_170_SIZE_LIMIT)\e[0m"
    exceeded=true
  else
      echo -e "\e[32m✅ $contract (deployed bytecode size: $deployed_size) is within the EIP-170 size limit ($EIP_170_SIZE_LIMIT)\e[0m"
  fi
done

if $exceeded; then
  exit 1
fi
